CREATE DATABASE HibernateBeta
GO
USE HibernateBeta
GO

CREATE TABLE Loai(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(50)
)

CREATE TABLE SanPham(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(50),
	Gia FLOAT,
	MoTa NVARCHAR(50),
	IdLoai int
)

CREATE TABLE NSX(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(50),
	QuocGia NVARCHAR(50)
)


CREATE TABLE SanPham_NSX(
	Id INT PRIMARY KEY IDENTITY(1,1),
	IdSP INT,
	IdNSX INT
)

ALTER TABLE dbo.SanPham ADD CONSTRAINT Fk_SP_Loai FOREIGN KEY(IdLoai) REFERENCES dbo.Loai(Id)
ALTER TABLE dbo.SanPham_NSX ADD CONSTRAINT FK_SanPham_NSX_SP FOREIGN KEY(IdSP) REFERENCES dbo.SanPham(Id)
ALTER TABLE dbo.SanPham_NSX ADD CONSTRAINT FK_SanPham_NSX_NSX FOREIGN KEY(IdNSX) REFERENCES dbo.NSX(Id)