/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class HomFrm extends javax.swing.JFrame {

    ArrayList<JPanel> lstPanel = new ArrayList<>();

    public HomFrm() {
        initComponents();
        setLocationRelativeTo(null);

        initPanel();
        tileName();
    }
    
    
    public void  tileName(){
        new Thread(){
            @Override
            public void run(){
                while (true) {                    
                    int i = (int) (Math.random() *10);
                    if (i == 1) {
                        lblTxt.setForeground(Color.red);
                    }
                    if (i == 2) {
                        lblTxt.setForeground(Color.MAGENTA);
                    }
                    if (i == 3) {
                        lblTxt.setForeground(Color.CYAN);
                    }
                    if (i == 4) {
                        lblTxt.setForeground(Color.PINK);
                    }
                    if (i == 5) {
                        lblTxt.setForeground(Color.ORANGE);
                    }
                    if (i == 6) {
                        lblTxt.setForeground(Color.blue);
                    }
                    if (i == 7) {
                        lblTxt.setForeground(Color.PINK);
                    }
                    if (i == 8) {
                        lblTxt.setForeground(Color.DARK_GRAY);
                    }
                    if (i == 9) {
                        lblTxt.setForeground(Color.green);
                    }
                    
                    try {
                        Thread.sleep(150);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomFrm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                
            }
        }.start();
                
    }

    public void initPanel() {
        QuanLySinhVienPanel qlsvp = new QuanLySinhVienPanel();
        QuanLyDiemSinhVienPanel qldsvp = new QuanLyDiemSinhVienPanel();
        PanelHome.add(qlsvp);
        PanelHome.add(qldsvp);
        lstPanel.add(qlsvp);
        lstPanel.add(qldsvp);

    }

    public void showPanel(int index) {
        for (JPanel panel : lstPanel) {
            panel.setVisible(false);
        }
        lstPanel.get(index).setVisible(true);
    }

    public void showCC(String cc, String acc) {
        if (cc.equalsIgnoreCase("DT")) {
            mnQldiem.setEnabled(false);
            showPanel(0);
            lblAcc.setText("Xin chào: " + acc);
            JOptionPane.showMessageDialog(this, "Bạn Đang Đăng Nhập Dưới Account Đào Tạo Bạn Chỉ Có Thể Quản Lý Sinh Viên");

        }
        if (cc.equalsIgnoreCase("GV")) {
            mnQlsv.setEnabled(false);
            showPanel(1);
            lblAcc.setText("Xin chào: " + acc);
            JOptionPane.showMessageDialog(this, "Bạn Đang Đăng Nhập Dưới Account Giảng Viên Bạn Chỉ Có Thể Sửa Điểm Sinh Viên");

        }
        if (cc.equalsIgnoreCase("admin")) {
            showPanel(0);
            lblAcc.setText("Xin chào: " + acc);
            JOptionPane.showMessageDialog(this, "Bạn Đang Đăng Nhập Dưới Account Admin Full Quyền");

        }

    }

    public void logOut() {
        this.dispose();
        JOptionPane.showMessageDialog(this, "Đăng Xuất Thành Công", "Logout", 1, new ImageIcon("src\\Icon\\log-out.png"));
        new LoginFrm().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        lblTxt = new javax.swing.JLabel();
        lblAcc = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnQldiem = new javax.swing.JMenuItem();
        mnQlsv = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnGioiThieu = new javax.swing.JMenuItem();
        mnLienHe = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTxt.setFont(new java.awt.Font("UTM Ong Do Gia", 1, 28)); // NOI18N
        lblTxt.setText("Hệ Thống Quản Lý Sinh Viên");

        lblAcc.setText("Xin chào:  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(lblTxt)
                .addGap(78, 78, 78)
                .addComponent(lblAcc)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAcc)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PanelHome.setLayout(new java.awt.CardLayout());

        jMenu1.setText("Hệ Thống");

        mnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/log-out.png"))); // NOI18N
        mnLogout.setText("Đăng Xuất");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        mnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit (1).png"))); // NOI18N
        mnExit.setText("Thoát");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnQldiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnQldiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exam.png"))); // NOI18N
        mnQldiem.setText("Quản Lý Điểm");
        mnQldiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQldiemActionPerformed(evt);
            }
        });
        jMenu2.add(mnQldiem);

        mnQlsv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnQlsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/student (1).png"))); // NOI18N
        mnQlsv.setText("Quản Lý Sinh Viên");
        mnQlsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQlsvActionPerformed(evt);
            }
        });
        jMenu2.add(mnQlsv);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ Giúp");

        mnGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/information (1).png"))); // NOI18N
        mnGioiThieu.setText("Giới Thiệu");
        mnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(mnGioiThieu);

        mnLienHe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnLienHe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/question.png"))); // NOI18N
        mnLienHe.setText("Liên Hệ");
        mnLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLienHeActionPerformed(evt);
            }
        });
        jMenu3.add(mnLienHe);

        jMenuItem1.setText("ShutDown");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnQldiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQldiemActionPerformed
        lblTxt.setText("Hệ Thống Quản Lý Điểm Sinh Viên");
        showPanel(1);
    }//GEN-LAST:event_mnQldiemActionPerformed

    private void mnQlsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQlsvActionPerformed
        lblTxt.setText("Hệ Thống Quản Lý Sinh Viên");
        showPanel(0);
    }//GEN-LAST:event_mnQlsvActionPerformed

    private void mnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGioiThieuActionPerformed
        new GioiThieuDl(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mnGioiThieuActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        logOut();
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLienHeActionPerformed
        Runtime run = Runtime.getRuntime();

        String url = "https://www.facebook.com/1011228384";

        try {
            run.exec("rundll32 url.dll, FileProtocolHandler " + url);
        } catch (IOException ex) {
            Logger.getLogger(HomFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnLienHeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Runtime run = Runtime.getRuntime();
        try {
            Process proc = run.exec("shutdown -a");
        } catch (IOException ex) {
            Logger.getLogger(HomFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblAcc;
    private javax.swing.JLabel lblTxt;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnGioiThieu;
    private javax.swing.JMenuItem mnLienHe;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnQldiem;
    private javax.swing.JMenuItem mnQlsv;
    // End of variables declaration//GEN-END:variables
}
