/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI2_JAVA_SWING;

import java.awt.Color;

/**
 *
 * @author Dungna89
 */
public class B2_JFrameButton extends javax.swing.JFrame {

  /**
   * Creates new form B2_JFrameButton
   */
  public B2_JFrameButton() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_BamVaoDay = new javax.swing.JButton();
        lbl_TenNhan = new javax.swing.JLabel();
        btn_red = new javax.swing.JButton();
        btn_black = new javax.swing.JButton();
        btn_blue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_BamVaoDay.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_BamVaoDay.setText("Bấm vào đây");
        btn_BamVaoDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BamVaoDayActionPerformed(evt);
            }
        });

        lbl_TenNhan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_TenNhan.setText("jLabel1");

        btn_red.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_red.setText("RED");

        btn_black.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_black.setText("BLACK");
        btn_black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blackActionPerformed(evt);
            }
        });

        btn_blue.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_blue.setText("BLUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TenNhan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_BamVaoDay)
                        .addGap(146, 146, 146)
                        .addComponent(btn_red)))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_black)
                .addGap(246, 246, 246))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(566, Short.MAX_VALUE)
                    .addComponent(btn_blue)
                    .addGap(249, 249, 249)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_TenNhan)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_BamVaoDay))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_red)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btn_black)
                .addGap(156, 156, 156))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(btn_blue)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btn_BamVaoDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BamVaoDayActionPerformed
    System.out.println("Đã bấm vào đây nè");
    lbl_TenNhan.setText("Tôi sẽ qua môn java 2");
  }//GEN-LAST:event_btn_BamVaoDayActionPerformed

  private void btn_blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blackActionPerformed
     this.getContentPane().setBackground(Color.black);
  }//GEN-LAST:event_btn_blackActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new B2_JFrameButton().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BamVaoDay;
    private javax.swing.JButton btn_black;
    private javax.swing.JButton btn_blue;
    private javax.swing.JButton btn_red;
    private javax.swing.JLabel lbl_TenNhan;
    // End of variables declaration//GEN-END:variables
}
